baseURL: "/"
title: Ajay Dhungel
paginate: 6
theme: charlolamode



menu:
    main:
        - name: Articles
          url: blog/
        - name: About
          url: about/
        - name: Certifications
          url: certifications/
        


params:
    author: Ajay Dhungel
    profile-description: Hi, I am Ajay Dhungel. I am a Cloud & DevOps enthusiast.
    defaultTheme: auto
    #disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Ajay Dhungel 
        imageUrl: "/images/profile.jpg"
        imageTitle: Ajay 
        imageWidth: 200
        imageHeight: 200
        buttons:
            #- name: Don't click me
            # url: https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley
            
    mainSections: []

    socialIcons:
        - name: github
          url: "https://github.com/ajaydhungel7"
        - name: twitter
          url: "https://x.com/ajaydgl"
        - name: linkedin
          url: "https://www.linkedin.com/in/ajaydhungel/"
        - name: buymeacoffee
          url: "https://buymeacoffee.com/ajaydhungel7"
        - name: instagram
          url: "https://www.instagram.com/ajaya_023/"
        - name: upwork
          url: "https://www.upwork.com/freelancers/~018b23e5bb6885caf7?viewMode=1"


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/profile.jpeg"
          favicon16x16: "/images/signature.png"
          favicon32x32: "/images/signature.png"
          apple_touch_icon: "/images/signature.png"
          safari_pinned_tab: "/images/signature.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
